const FAKE_MENU = {
	weekDays: [
		{
			weekDay: "Mon",
			userName: null,
			orderedDishes: [],
			isHoliday: false,
			suppliers: [
				{
					supplierId: 1,
					supplierName: "Столовая №1",
					availableMoneyToOrder: 51,
					canMultiSelect: true,
					categories: [
						{
							id: 7,
							name: "ГАРНИРЫ",
							dishes: [
								{
									id: 2,
									name: "Картофельное вареный15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 13,
									name: "Гречневая каша 12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 27,
									name: "Капуста тушеная 16",
									price: 16.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 28,
									name: "Рагу овощное150гр20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 29,
									name: "Фасоль 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 51,
									name: "Лазанья38",
									price: 38.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 52,
									name: "Картофель по-криольски15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 54,
									name: "Пшеничная каша12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 6,
							name: "МЯСНОЕ",
							dishes: [
								{
									id: 4,
									name: "Стейк свиной 150гр34",
									price: 34.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 5,
									name: "Жареное бедро/крыло куриное200гр44",
									price: 44.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 6,
									name: '"Бризоль" свинина рубленая в яйце22',
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 8,
									name: "Утка с яблоками и черносливом(200гр) 64",
									price: 64.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 14,
									name: "Шашлык курин 100гр/28",
									price: 28.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 15,
									name: "Свинина по французки34",
									price: 34.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 16,
									name: "Шашлык свин.100го/36",
									price: 36.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 17,
									name: "Бифштекс с яйцом24",
									price: 24.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 18,
									name: "Чикенштекс24",
									price: 24.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 19,
									name: "Люля куриный27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 20,
									name: "Люля свин.27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 21,
									name: "Тефтели20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 22,
									name: "Котл. Куриная22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 23,
									name: "Котл. Свиная22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 26,
									name: "Рыба жарен 100гр /хек/22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 10,
							name: "НАПИТКИ",
							dishes: [
								{
									id: 30,
									name: "Узвар 7",
									price: 7.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 56,
									name: "Компот 7",
									price: 7.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 113,
									name: "Сок 8",
									price: 8.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 9,
							name: "ПИРОГИ",
							dishes: [
								{
									id: 31,
									name: "Мини-пицца12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 32,
									name: "Сосиска в тесте 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 33,
									name: "Пирог с творогом 6",
									price: 6.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 34,
									name: "Пирог с вишней / малина10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 35,
									name: "Пирог с фруктами 6",
									price: 6.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 36,
									name: "Пирог Мак 8",
									price: 8.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 37,
									name: "Пирог с грибами 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 38,
									name: "Пирог Картошка 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 39,
									name: "Пирог Капуста 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 40,
									name: "Пирог Мясо 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 8,
							name: "ДЕСЕРТЫ",
							dishes: [
								{
									id: 41,
									name: "Блинчик с мясом 14",
									price: 14.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 42,
									name: "Блинчик с творогом 12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 43,
									name: "Торт из сыра Буко23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 44,
									name: "Запеканка творожная с грушей/яблоко и корицей 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 46,
									name: "Торт (сметанник/сникерс/шоколадный/тирамису/чизкейк) 23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 47,
									name: "Сырник 1шт12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 48,
									name: "Фруктово-желейный23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 49,
									name: "Торт «Наполеон»20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 5,
							name: "ПЕРВОЕ",
							dishes: [
								{
									id: 58,
									name: "Борщ14",
									price: 14.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 87,
									name: "Бульон18",
									price: 18.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 112,
									name: "Суп гороховый18",
									price: 18.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},

						{
							id: 4,
							name: "САЛАТЫ",
							dishes: [
								{
									id: 88,
									name: "Корейская морковка 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 89,
									name: "Квашеная капуста 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 90,
									name: "Салат из свежей Капусты10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 91,
									name: "Салат из помидора и огурца 15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 92,
									name: "Свекла 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 93,
									name: "Крабовый салат 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 94,
									name: "Оливье 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 95,
									name: "Шуба 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
					],
				},
				{
					supplierId: 2,
					supplierName: "ГлаголЪ",
					availableMoneyToOrder: 56,
					canMultiSelect: false,
					categories: [
						{
							id: 1,
							name: "Первые блюда",
							dishes: [
								{
									id: 1,
									name: "Суп гречневый",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 73,
									name: "Компот",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 78,
									name: "Борщ",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 2,
							name: "Вторые блюда",
							dishes: [
								{
									id: 62,
									name: "Запеченый картофель + котлета куриная",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 67,
									name: "Рис + отбивная куриная с помидором",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 72,
									name: "Спагетти + тефтеля",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 3,
							name: "Салаты, пирожки",
							dishes: [
								{
									id: 84,
									name: "Салат свежий (капуста,огурец,морковь)",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 96,
									name: "Пирожок картофель",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 97,
									name: "Пирожок слива",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 98,
									name: "Пирожок рис+яйцо",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 99,
									name: "Пирожок корица",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 100,
									name: "Пирожок мак",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 101,
									name: "Пирожок смородина",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 102,
									name: "Пирожок ветчина-сыр",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 103,
									name: "Пирожок с творогом",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 104,
									name: "Пирожок с капустой",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 109,
									name: "Салат оливье",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
					],
				},
			],
		},
		{
			weekDay: "Tue",
			userName: null,
			orderedDishes: [],
			isHoliday: false,
			suppliers: [
				{
					supplierId: 1,
					supplierName: "Столовая №1",
					availableMoneyToOrder: 51,
					canMultiSelect: true,
					categories: [
						{
							id: 7,
							name: "ГАРНИРЫ",
							dishes: [
								{
									id: 2,
									name: "Картофельное вареный15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 13,
									name: "Гречневая каша 12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 27,
									name: "Капуста тушеная 16",
									price: 16.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 28,
									name: "Рагу овощное150гр20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 29,
									name: "Фасоль 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 50,
									name: "Лазанья36",
									price: 36.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 52,
									name: "Картофель по-криольски15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 53,
									name: "Картофель жареный с луком15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 6,
							name: "МЯСНОЕ",
							dishes: [
								{
									id: 4,
									name: "Стейк свиной 150гр34",
									price: 34.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 5,
									name: "Жареное бедро/крыло куриное200гр44",
									price: 44.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 6,
									name: '"Бризоль" свинина рубленая в яйце22',
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 7,
									name: "лазанья 38",
									price: 38.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 12,
									name: "Биточки свиные по-домашнему20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 15,
									name: "Свинина по французки34",
									price: 34.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 16,
									name: "Шашлык свин.100го/36",
									price: 36.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 17,
									name: "Бифштекс с яйцом24",
									price: 24.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 18,
									name: "Чикенштекс24",
									price: 24.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 19,
									name: "Люля куриный27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 20,
									name: "Люля свин.27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 21,
									name: "Тефтели20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 22,
									name: "Котл. Куриная22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 23,
									name: "Котл. Свиная22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 26,
									name: "Рыба жарен 100гр /хек/22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 10,
							name: "НАПИТКИ",
							dishes: [
								{
									id: 30,
									name: "Узвар 7",
									price: 7.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 56,
									name: "Компот 7",
									price: 7.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 113,
									name: "Сок 8",
									price: 8.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 9,
							name: "ПИРОГИ",
							dishes: [
								{
									id: 31,
									name: "Мини-пицца12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 32,
									name: "Сосиска в тесте 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 33,
									name: "Пирог с творогом 6",
									price: 6.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 34,
									name: "Пирог с вишней / малина10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 35,
									name: "Пирог с фруктами 6",
									price: 6.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 36,
									name: "Пирог Мак 8",
									price: 8.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 37,
									name: "Пирог с грибами 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 38,
									name: "Пирог Картошка 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 39,
									name: "Пирог Капуста 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 40,
									name: "Пирог Мясо 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 8,
							name: "ДЕСЕРТЫ",
							dishes: [
								{
									id: 41,
									name: "Блинчик с мясом 14",
									price: 14.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 42,
									name: "Блинчик с творогом 12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 43,
									name: "Торт из сыра Буко23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 44,
									name: "Запеканка творожная с грушей/яблоко и корицей 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 45,
									name: "Торт (сметанник/сникерс/шоколадный/тирамису) 23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 47,
									name: "Сырник 1шт12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 48,
									name: "Фруктово-желейный23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 49,
									name: "Торт «Наполеон»20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 5,
							name: "ПЕРВОЕ",
							dishes: [
								{
									id: 57,
									name: "Суп харчо20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 58,
									name: "Борщ14",
									price: 14.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 87,
									name: "Бульон18",
									price: 18.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 4,
							name: "САЛАТЫ",
							dishes: [
								{
									id: 88,
									name: "Корейская морковка 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 89,
									name: "Квашеная капуста 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 90,
									name: "Салат из свежей Капусты10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 91,
									name: "Салат из помидора и огурца 15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 92,
									name: "Свекла 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 93,
									name: "Крабовый салат 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 94,
									name: "Оливье 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 95,
									name: "Шуба 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
					],
				},
				{
					supplierId: 2,
					supplierName: "ГлаголЪ",
					availableMoneyToOrder: 56,
					canMultiSelect: false,
					categories: [
						{
							id: 2,
							name: "Вторые блюда",
							dishes: [
								{
									id: 61,
									name: "Гречневая каша с овощами + биточек с сыром",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 66,
									name: "Пюре + куриный рулет с овощами",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 83,
									name: "Плов",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 1,
							name: "Первые блюда",
							dishes: [
								{
									id: 73,
									name: "Компот",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 77,
									name: "Суп сырный",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 82,
									name: "Суп грибной",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 3,
							name: "Салаты, пирожки",
							dishes: [
								{
									id: 85,
									name: "Салат овощная нарезка",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 96,
									name: "Пирожок картофель",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 97,
									name: "Пирожок слива",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 98,
									name: "Пирожок рис+яйцо",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 99,
									name: "Пирожок корица",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 100,
									name: "Пирожок мак",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 101,
									name: "Пирожок смородина",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 102,
									name: "Пирожок ветчина-сыр",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 103,
									name: "Пирожок с творогом",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 104,
									name: "Пирожок с капустой",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 108,
									name: "Салат Лисичка (морковь,огурец,сыр,курица)",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
					],
				},
			],
		},
		{
			weekDay: "Wed",
			userName: null,
			orderedDishes: [],
			isHoliday: false,
			suppliers: [
				{
					supplierId: 1,
					supplierName: "Столовая №1",
					availableMoneyToOrder: 51,
					canMultiSelect: true,
					categories: [
						{
							id: 7,
							name: "ГАРНИРЫ",
							dishes: [
								{
									id: 2,
									name: "Картофельное вареный15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 13,
									name: "Гречневая каша 12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 27,
									name: "Капуста тушеная 16",
									price: 16.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 28,
									name: "Рагу овощное150гр20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 29,
									name: "Фасоль 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 52,
									name: "Картофель по-криольски15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 54,
									name: "Пшеничная каша12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 6,
							name: "МЯСНОЕ",
							dishes: [
								{
									id: 3,
									name: "Стейк свиной 150гр32",
									price: 32.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 5,
									name: "Жареное бедро/крыло куриное200гр44",
									price: 44.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 6,
									name: '"Бризоль" свинина рубленая в яйце22',
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 8,
									name: "Утка с яблоками и черносливом(200гр) 64",
									price: 64.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 11,
									name: "Ленивые голубцы 25",
									price: 25.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 15,
									name: "Свинина по французки34",
									price: 34.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 16,
									name: "Шашлык свин.100го/36",
									price: 36.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 17,
									name: "Бифштекс с яйцом24",
									price: 24.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 18,
									name: "Чикенштекс24",
									price: 24.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 19,
									name: "Люля куриный27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 20,
									name: "Люля свин.27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 21,
									name: "Тефтели20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 22,
									name: "Котл. Куриная22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 23,
									name: "Котл. Свиная22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 26,
									name: "Рыба жарен 100гр /хек/22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 10,
							name: "НАПИТКИ",
							dishes: [
								{
									id: 30,
									name: "Узвар 7",
									price: 7.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 56,
									name: "Компот 7",
									price: 7.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 113,
									name: "Сок 8",
									price: 8.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 9,
							name: "ПИРОГИ",
							dishes: [
								{
									id: 31,
									name: "Мини-пицца12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 32,
									name: "Сосиска в тесте 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 33,
									name: "Пирог с творогом 6",
									price: 6.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 34,
									name: "Пирог с вишней / малина10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 35,
									name: "Пирог с фруктами 6",
									price: 6.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 36,
									name: "Пирог Мак 8",
									price: 8.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 37,
									name: "Пирог с грибами 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 38,
									name: "Пирог Картошка 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 39,
									name: "Пирог Капуста 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 40,
									name: "Пирог Мясо 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 8,
							name: "ДЕСЕРТЫ",
							dishes: [
								{
									id: 41,
									name: "Блинчик с мясом 14",
									price: 14.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 42,
									name: "Блинчик с творогом 12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 45,
									name: "Торт (сметанник/сникерс/шоколадный/тирамису) 23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 47,
									name: "Сырник 1шт12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 48,
									name: "Фруктово-желейный23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 49,
									name: "Торт «Наполеон»20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 5,
							name: "ПЕРВОЕ",
							dishes: [
								{
									id: 55,
									name: "Лагман30",
									price: 30.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 58,
									name: "Борщ14",
									price: 14.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 87,
									name: "Бульон18",
									price: 18.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 4,
							name: "САЛАТЫ",
							dishes: [
								{
									id: 88,
									name: "Корейская морковка 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 89,
									name: "Квашеная капуста 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 90,
									name: "Салат из свежей Капусты10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 91,
									name: "Салат из помидора и огурца 15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 92,
									name: "Свекла 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 93,
									name: "Крабовый салат 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 94,
									name: "Оливье 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 95,
									name: "Шуба 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
					],
				},
				{
					supplierId: 2,
					supplierName: "ГлаголЪ",
					availableMoneyToOrder: 56,
					canMultiSelect: false,
					categories: [
						{
							id: 2,
							name: "Вторые блюда",
							dishes: [
								{
									id: 60,
									name: "Омлет с ветчиной и сыром",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 65,
									name: "Тушеная капуста с колбасками",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 71,
									name: "Отварно картофель + отбивная куриная",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 1,
							name: "Первые блюда",
							dishes: [
								{
									id: 73,
									name: "Компот",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 76,
									name: "Суп овощной",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 81,
									name: "Суп гороховый",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 3,
							name: "Салаты, пирожки",
							dishes: [
								{
									id: 86,
									name: "Салат винегрет",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 96,
									name: "Пирожок картофель",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 97,
									name: "Пирожок слива",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 98,
									name: "Пирожок рис+яйцо",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 99,
									name: "Пирожок корица",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 100,
									name: "Пирожок мак",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 101,
									name: "Пирожок смородина",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 102,
									name: "Пирожок ветчина-сыр",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 103,
									name: "Пирожок с творогом",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 104,
									name: "Пирожок с капустой",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 107,
									name: "Салат крабовый",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
					],
				},
			],
		},
		{
			weekDay: "Thu",
			userName: null,
			orderedDishes: [],
			isHoliday: true,
			suppliers: [
				{
					supplierId: 1,
					supplierName: "Столовая №1",
					availableMoneyToOrder: 51,
					canMultiSelect: true,
					categories: [
						{
							id: 7,
							name: "ГАРНИРЫ",
							dishes: [
								{
									id: 2,
									name: "Картофельное вареный15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 13,
									name: "Гречневая каша 12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 27,
									name: "Капуста тушеная 16",
									price: 16.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 28,
									name: "Рагу овощное150гр20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 29,
									name: "Фасоль 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 53,
									name: "Картофель жареный с луком15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 6,
							name: "МЯСНОЕ",
							dishes: [
								{
									id: 3,
									name: "Стейк свиной 150гр32",
									price: 32.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 5,
									name: "Жареное бедро/крыло куриное200гр44",
									price: 44.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 6,
									name: '"Бризоль" свинина рубленая в яйце22',
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 10,
									name: "Шашлык курин 100гр/25",
									price: 25.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 15,
									name: "Свинина по французки34",
									price: 34.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 16,
									name: "Шашлык свин.100го/36",
									price: 36.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 17,
									name: "Бифштекс с яйцом24",
									price: 24.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 18,
									name: "Чикенштекс24",
									price: 24.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 19,
									name: "Люля куриный27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 20,
									name: "Люля свин.27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 21,
									name: "Тефтели20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 22,
									name: "Котл. Куриная22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 23,
									name: "Котл. Свиная22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 26,
									name: "Рыба жарен 100гр /хек/22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 5,
							name: "ПЕРВОЕ",
							dishes: [
								{
									id: 25,
									name: "Юшка рыбацкая 27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 58,
									name: "Борщ14",
									price: 14.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 87,
									name: "Бульон18",
									price: 18.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 10,
							name: "НАПИТКИ",
							dishes: [
								{
									id: 30,
									name: "Узвар 7",
									price: 7.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 56,
									name: "Компот 7",
									price: 7.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 113,
									name: "Сок 8",
									price: 8.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 9,
							name: "ПИРОГИ",
							dishes: [
								{
									id: 31,
									name: "Мини-пицца12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 32,
									name: "Сосиска в тесте 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 33,
									name: "Пирог с творогом 6",
									price: 6.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 34,
									name: "Пирог с вишней / малина10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 35,
									name: "Пирог с фруктами 6",
									price: 6.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 36,
									name: "Пирог Мак 8",
									price: 8.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 37,
									name: "Пирог с грибами 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 38,
									name: "Пирог Картошка 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 39,
									name: "Пирог Капуста 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 40,
									name: "Пирог Мясо 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 8,
							name: "ДЕСЕРТЫ",
							dishes: [
								{
									id: 41,
									name: "Блинчик с мясом 14",
									price: 14.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 42,
									name: "Блинчик с творогом 12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 45,
									name: "Торт (сметанник/сникерс/шоколадный/тирамису) 23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 47,
									name: "Сырник 1шт12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 48,
									name: "Фруктово-желейный23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 49,
									name: "Торт «Наполеон»20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 4,
							name: "САЛАТЫ",
							dishes: [
								{
									id: 88,
									name: "Корейская морковка 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 89,
									name: "Квашеная капуста 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 90,
									name: "Салат из свежей Капусты10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 91,
									name: "Салат из помидора и огурца 15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 92,
									name: "Свекла 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 93,
									name: "Крабовый салат 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 94,
									name: "Оливье 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 95,
									name: "Шуба 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
					],
				},
				{
					supplierId: 2,
					supplierName: "ГлаголЪ",
					availableMoneyToOrder: 56,
					canMultiSelect: false,
					categories: [
						{
							id: 2,
							name: "Вторые блюда",
							dishes: [
								{
									id: 59,
									name: "Рис с овощами + печень куриная",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 64,
									name: "Блины с курицей и грибами",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 69,
									name: "Вареники с мясом",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 1,
							name: "Первые блюда",
							dishes: [
								{
									id: 73,
									name: "Компот",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 75,
									name: "Суп с вермишелью",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 80,
									name: "Харчо",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 3,
							name: "Салаты, пирожки",
							dishes: [
								{
									id: 96,
									name: "Пирожок картофель",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 97,
									name: "Пирожок слива",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 98,
									name: "Пирожок рис+яйцо",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 99,
									name: "Пирожок корица",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 100,
									name: "Пирожок мак",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 101,
									name: "Пирожок смородина",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 102,
									name: "Пирожок ветчина-сыр",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 103,
									name: "Пирожок с творогом",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 104,
									name: "Пирожок с капустой",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 106,
									name: "Салат шуба",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 111,
									name: "Салат свекла с сыром и сметаной",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
					],
				},
			],
		},
		{
			weekDay: "Fri",
			userName: null,
			orderedDishes: [],
			isHoliday: false,
			suppliers: [
				{
					supplierId: 1,
					supplierName: "Столовая №1",
					availableMoneyToOrder: 51,
					canMultiSelect: true,
					categories: [
						{
							id: 7,
							name: "ГАРНИРЫ",
							dishes: [
								{
									id: 2,
									name: "Картофельное вареный15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 13,
									name: "Гречневая каша 12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 27,
									name: "Капуста тушеная 16",
									price: 16.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 28,
									name: "Рагу овощное150гр20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 29,
									name: "Фасоль 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 54,
									name: "Пшеничная каша12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 6,
							name: "МЯСНОЕ",
							dishes: [
								{
									id: 3,
									name: "Стейк свиной 150гр32",
									price: 32.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 5,
									name: "Жареное бедро/крыло куриное200гр44",
									price: 44.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 6,
									name: '"Бризоль" свинина рубленая в яйце22',
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 9,
									name: "Скумбрия100гр/25",
									price: 25.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 15,
									name: "Свинина по французки34",
									price: 34.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 16,
									name: "Шашлык свин.100го/36",
									price: 36.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 17,
									name: "Бифштекс с яйцом24",
									price: 24.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 18,
									name: "Чикенштекс24",
									price: 24.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 19,
									name: "Люля куриный27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 20,
									name: "Люля свин.27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 21,
									name: "Тефтели20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 22,
									name: "Котл. Куриная22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 23,
									name: "Котл. Свиная22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 26,
									name: "Рыба жарен 100гр /хек/22",
									price: 22.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 5,
							name: "ПЕРВОЕ",
							dishes: [
								{
									id: 24,
									name: "Солянка27",
									price: 27.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 58,
									name: "Борщ14",
									price: 14.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 87,
									name: "Бульон18",
									price: 18.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 10,
							name: "НАПИТКИ",
							dishes: [
								{
									id: 30,
									name: "Узвар 7",
									price: 7.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 56,
									name: "Компот 7",
									price: 7.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 113,
									name: "Сок 8",
									price: 8.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 9,
							name: "ПИРОГИ",
							dishes: [
								{
									id: 31,
									name: "Мини-пицца12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 32,
									name: "Сосиска в тесте 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 33,
									name: "Пирог с творогом 6",
									price: 6.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 34,
									name: "Пирог с вишней / малина10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 35,
									name: "Пирог с фруктами 6",
									price: 6.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 36,
									name: "Пирог Мак 8",
									price: 8.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 37,
									name: "Пирог с грибами 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 38,
									name: "Пирог Картошка 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 39,
									name: "Пирог Капуста 5",
									price: 5.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 40,
									name: "Пирог Мясо 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 8,
							name: "ДЕСЕРТЫ",
							dishes: [
								{
									id: 41,
									name: "Блинчик с мясом 14",
									price: 14.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 42,
									name: "Блинчик с творогом 12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 45,
									name: "Торт (сметанник/сникерс/шоколадный/тирамису) 23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 47,
									name: "Сырник 1шт12",
									price: 12.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 48,
									name: "Фруктово-желейный23",
									price: 23.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 49,
									name: "Торт «Наполеон»20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 4,
							name: "САЛАТЫ",
							dishes: [
								{
									id: 88,
									name: "Корейская морковка 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 89,
									name: "Квашеная капуста 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 90,
									name: "Салат из свежей Капусты10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 91,
									name: "Салат из помидора и огурца 15",
									price: 15.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 92,
									name: "Свекла 10",
									price: 10.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 93,
									name: "Крабовый салат 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 94,
									name: "Оливье 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 95,
									name: "Шуба 20",
									price: 20.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
					],
				},
				{
					supplierId: 2,
					supplierName: "ГлаголЪ",
					availableMoneyToOrder: 56,
					canMultiSelect: false,
					categories: [
						{
							id: 2,
							name: "Вторые блюда",
							dishes: [
								{
									id: 63,
									name: "Пюре + тефтеля",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 68,
									name: "Паста с ветчиной и грибами",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 70,
									name: "Гречневая каша+ отбивная куриная в сыре",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 1,
							name: "Первые блюда",
							dishes: [
								{
									id: 73,
									name: "Компот",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 74,
									name: "Суп с фрикадельками",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 79,
									name: "Кулеш",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
						{
							id: 3,
							name: "Салаты, пирожки",
							dishes: [
								{
									id: 96,
									name: "Пирожок картофель",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 97,
									name: "Пирожок слива",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 98,
									name: "Пирожок рис+яйцо",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 99,
									name: "Пирожок корица",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 100,
									name: "Пирожок мак",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 101,
									name: "Пирожок смородина",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 102,
									name: "Пирожок ветчина-сыр",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 103,
									name: "Пирожок с творогом",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 104,
									name: "Пирожок с капустой",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 105,
									name: "Салат Миледи(пек.капуст,ветчина,огурец,кукуруза",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
								{
									id: 110,
									name: "Салат с пекинской капустой и овощами",
									price: 0.0,
									negativeRewievs: 0,
									positiveRewievs: 0,
									weekDay: null,
								},
							],
						},
					],
				},
			],
		},
	],
};

export default FAKE_MENU;
